#cloud-config

users:
  - default

  - name: tux
    gecos: Tux
    groups:
      - sudo
      - adm
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true

package_update: true
package_upgrade: true

packages:
  - ansible-core
  - git
  - curl
  - python3-pip
  - python3-venv

runcmd:
  - ansible --version > /root/ansible-version.txt
