#!/bin/sh

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

VENV="$SCRIPT_DIR/.venv"

if [ ! -d "$VENV" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV"

    "$VENV/bin/pip" install --upgrade pip
    "$VENV/bin/pip" install -r "$SCRIPT_DIR/requirements.txt"
fi

# exec "$VENV/bin/python" "$SCRIPT_DIR/hetzner.py" "$@"

OUTPUT=$("$VENV/bin/python" "$SCRIPT_DIR/hetzner.py" "$@")

echo "$OUTPUT"

EXPORT_LINE=$(echo "$OUTPUT" | grep '^export HETZNER_SERVER_IP=')

if [ -n "$EXPORT_LINE" ]; then
    eval "$EXPORT_LINE"
    export HETZNER_SERVER_IP
    echo "HETZNER_SERVER_IP=$HETZNER_SERVER_IP"
fi

# ssh-keygen -R "$IP" >/dev/null 2>&3
